### Himanshu Baweja

### E20CSE212

### Week 4 Lab 1

In [16]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_recall_fscore_support
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_squared_error
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler
from sklearn import preprocessing

In [17]:
data = pd.read_csv("dataset.csv")
feature_list=['Hour','Immobilized_bus','Broken_Truck','Vehicle_excess','Accident_victim','Running_over','Fire_vehicles','Occurrence_involving_freight','Incident_involving_dangerous_freight','Lack_of_electricity','Fire','Point_of_flooding','Manifestations','Defect_in_the_network_of_trolleybuses','Tree_on_the_road','Semaphore_off','Intermittent_Semaphore','Slowness_in_traffic_percent']
data.columns = feature_list
data

      Hour  ...  Slowness_in_traffic_percent
0    07:30  ...                          6.6
1    08:00  ...                          8.7
2    08:30  ...                          9.2
3    09:00  ...                         11.1
4    09:30  ...                         10.9
..     ...  ...                          ...
129  18:00  ...                         17.8
130  18:30  ...                         18.1
131  19:00  ...                         17.7
132  19:30  ...                         17.4
133  20:00  ...                         12.1

[134 rows x 18 columns]

In [18]:
morning =['07:30' ,'08:00', '08:30', '09:00', '09:30','10:00' ,'10:30' ,'11:00','07:00']
noon = ['11:30','12:00' ,'12:30' ,'13:00']
afternoon =['13:30', '14:00', '14:30' ,'15:00' ,'15:30' ,'16:00']
evening =['16:30', '17:00' ,'17:30' ,'18:00']
night =['18:30' ,'19:00' ,'19:30' ,'20:00']
data['Hour'].replace(to_replace = morning,value ="Morning",inplace =True)
data['Hour'].replace(to_replace = noon,value ="Noon",inplace =True)
data['Hour'].replace(to_replace = afternoon,value ="Afternoon",inplace =True)
data['Hour'].replace(to_replace = evening,value ="Evening",inplace =True)
data['Hour'].replace(to_replace = night,value ="Night",inplace =True)
data = pd.get_dummies(data, columns = ['Hour'])
data

     Immobilized_bus  Broken_Truck  ...  Hour_Night  Hour_Noon
0                  0             0  ...           0          0
1                  0             0  ...           0          0
2                  0             0  ...           0          0
3                  0             0  ...           0          0
4                  0             0  ...           0          0
..               ...           ...  ...         ...        ...
129                1             0  ...           0          0
130                0             0  ...           1          0
131                1             0  ...           1          0
132                0             4  ...           1          0
133                0             0  ...           1          0

[134 rows x 22 columns]

In [19]:

X = data[['Immobilized_bus', 'Broken_Truck', 'Vehicle_excess', 'Accident_victim',
       'Running_over', 'Fire_vehicles', 'Occurrence_involving_freight',
       'Incident_involving_dangerous_freight', 'Lack_of_electricity', 'Fire',
       'Point_of_flooding', 'Manifestations',
       'Defect_in_the_network_of_trolleybuses', 'Tree_on_the_road',
       'Semaphore_off', 'Intermittent_Semaphore', 'Hour_Afternoon', 'Hour_Evening',
       'Hour_Morning', 'Hour_Night', 'Hour_Noon']]
X

     Immobilized_bus  Broken_Truck  ...  Hour_Night  Hour_Noon
0                  0             0  ...           0          0
1                  0             0  ...           0          0
2                  0             0  ...           0          0
3                  0             0  ...           0          0
4                  0             0  ...           0          0
..               ...           ...  ...         ...        ...
129                1             0  ...           0          0
130                0             0  ...           1          0
131                1             0  ...           1          0
132                0             4  ...           1          0
133                0             0  ...           1          0

[134 rows x 21 columns]

In [20]:
scaler = MinMaxScaler()
scaler.fit(X)
X = scaler.transform(X)

In [21]:
Y = data.Slowness_in_traffic_percent
Y

0       6.6
1       8.7
2       9.2
3      11.1
4      10.9
       ...
129    17.8
130    18.1
131    17.7
132    17.4
133    12.1
Name: Slowness_in_traffic_percent, Length: 134, dtype: float64

In [22]:
x_train, x_test, y_train, y_test = train_test_split(X[:,17:22], Y, train_size=108, shuffle=False)

In [23]:
model = LinearRegression()
model.fit(x_train, y_train)
y_pred = model.predict(x_test)
mse = mean_squared_error(y_test,y_pred)
print(f"\nMSE: {mse}")

MSE: 7.7286181594254515

In [24]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import median_absolute_error
from sklearn.metrics import r2_score
poly = PolynomialFeatures(degree = 2)
X_poly = poly.fit_transform(X[:,17:22])
x_train1, x_test1, y_train1, y_test1 = train_test_split(X_poly, Y, train_size=108, shuffle = False)
model = LinearRegression()
model.fit(x_train1,y_train1)
y_pred = model.predict(x_test1)
mse = mean_squared_error(y_test1,y_pred)
print(f"\nMSE: {mse}")
rmse = mean_squared_error(y_test1,y_pred,squared=False)
print(f"\nRMSE: {rmse}")
mea = mean_absolute_error(y_test1,y_pred)
print(f"\nMEA: {mea}")
mdea = median_absolute_error(y_test1,y_pred)
print(f"\nMDEA: {mdea}")
r2 = r2_score(y_test1,y_pred)
print(f"\nR2 Square: {r2}")

MSE: 7.645759519311681

RMSE: 2.7650966564139634

MEA: 2.3233595343473437

MDEA: 2.0

R2 Square: 0.4278120792417637

In [25]:
percentage = [0.1,0.2,0.3,0.4]
for i in percentage:
    poly = PolynomialFeatures(degree = 2)
    X_poly = poly.fit_transform(X[:,17:22])
    x_train1, x_test1, y_train1, y_test1 = train_test_split(X_poly, Y, test_size=i, shuffle=False)
    model = LinearRegression()
    model.fit(x_train1,y_train1)
    y_pred = model.predict(x_test1)
    mse = mean_squared_error(y_test1,y_pred)
    print("MSE for %i percent test size is: %f "%(i*100,mse))

MSE for 10 percent test size is: 6.668039
MSE for 20 percent test size is: 7.924147
MSE for 30 percent test size is: 10.793057
MSE for 40 percent test size is: 9.010038

In [26]:
dg = [2,3,4,5,6,7,8,9,10,15,20]
percentage = [0.5,0.6,0.7,0.8,0.9]
for i in dg:
    poly = PolynomialFeatures(degree = i)
    X_poly = poly.fit_transform(X[:,17:22])
    for j in percentage:
        x_train1, x_test1, y_train1, y_test1 = train_test_split(X_poly, Y, train_size=j, shuffle=False)
        model = LinearRegression()
        model.fit(x_train1,y_train1)
        y_pred = model.predict(x_test1)
        mse = mean_squared_error(y_test1,y_pred)
        print("MSE for polynomial degree %i and training data size %i percent is: %f "%(i,j*100,mse))
    print("\n")

MSE for polynomial degree 2 and training data size 50 percent is: 19.832703
MSE for polynomial degree 2 and training data size 60 percent is: 9.010038
MSE for polynomial degree 2 and training data size 70 percent is: 10.793057
MSE for polynomial degree 2 and training data size 80 percent is: 7.924147
MSE for polynomial degree 2 and training data size 90 percent is: 6.668039


MSE for polynomial degree 3 and training data size 50 percent is: 19.832703
MSE for polynomial degree 3 and training data size 60 percent is: 9.010038
MSE for polynomial degree 3 and training data size 70 percent is: 10.793057
MSE for polynomial degree 3 and training data size 80 percent is: 7.924147
MSE for polynomial degree 3 and training data size 90 percent is: 6.668039


MSE for polynomial degree 4 and training data size 50 percent is: 20.190744
MSE for polynomial degree 4 and training data size 60 percent is: 9.010038
MSE for polynomial degree 4 and training data size 70 percent is: 10.793057
MSE for polynomial degree 4 and training data size 80 percent is: 7.924147
MSE for polynomial degree 4 and training data size 90 percent is: 6.668039


MSE for polynomial degree 5 and training data size 50 percent is: 19.832703
MSE for polynomial degree 5 and training data size 60 percent is: 9.010038
MSE for polynomial degree 5 and training data size 70 percent is: 11.126414
MSE for polynomial degree 5 and training data size 80 percent is: 7.924147
MSE for polynomial degree 5 and training data size 90 percent is: 6.668039


MSE for polynomial degree 6 and training data size 50 percent is: 19.832703
MSE for polynomial degree 6 and training data size 60 percent is: 9.010038
MSE for polynomial degree 6 and training data size 70 percent is: 10.793057
MSE for polynomial degree 6 and training data size 80 percent is: 17.527523
MSE for polynomial degree 6 and training data size 90 percent is: 6.599565


MSE for polynomial degree 7 and training data size 50 percent is: 19.832703
MSE for polynomial degree 7 and training data size 60 percent is: 11.302167
MSE for polynomial degree 7 and training data size 70 percent is: 10.793057
MSE for polynomial degree 7 and training data size 80 percent is: 7.924147
MSE for polynomial degree 7 and training data size 90 percent is: 6.668039


MSE for polynomial degree 8 and training data size 50 percent is: 19.832703
MSE for polynomial degree 8 and training data size 60 percent is: 9.010038
MSE for polynomial degree 8 and training data size 70 percent is: 10.793057
MSE for polynomial degree 8 and training data size 80 percent is: 7.924147
MSE for polynomial degree 8 and training data size 90 percent is: 6.668039


MSE for polynomial degree 9 and training data size 50 percent is: 19.832703
MSE for polynomial degree 9 and training data size 60 percent is: 8.615052
MSE for polynomial degree 9 and training data size 70 percent is: 10.793057
MSE for polynomial degree 9 and training data size 80 percent is: 7.924147
MSE for polynomial degree 9 and training data size 90 percent is: 6.588750


MSE for polynomial degree 10 and training data size 50 percent is: 19.899862
MSE for polynomial degree 10 and training data size 60 percent is: 9.010038
MSE for polynomial degree 10 and training data size 70 percent is: 10.790815
MSE for polynomial degree 10 and training data size 80 percent is: 7.528478
MSE for polynomial degree 10 and training data size 90 percent is: 6.668039


MSE for polynomial degree 15 and training data size 50 percent is: 19.830217
MSE for polynomial degree 15 and training data size 60 percent is: 9.010038
MSE for polynomial degree 15 and training data size 70 percent is: 10.793057
MSE for polynomial degree 15 and training data size 80 percent is: 8.084283
MSE for polynomial degree 15 and training data size 90 percent is: 6.886274


MSE for polynomial degree 20 and training data size 50 percent is: 28.950520
MSE for polynomial degree 20 and training data size 60 percent is: 37.971201
MSE for polynomial degree 20 and training data size 70 percent is: 10.711075
MSE for polynomial degree 20 and training data size 80 percent is: 10.567593
MSE for polynomial degree 20 and training data size 90 percent is: 6.594027

In [27]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import median_absolute_error
from sklearn.metrics import r2_score
poly = PolynomialFeatures(degree = 2)
X_poly = poly.fit_transform(X[:,17:22])
x_train1, x_test1, y_train1, y_test1 = train_test_split(X_poly, Y, train_size=0.2, shuffle=True)
model = LinearRegression()
model.fit(x_train1,y_train1)
y_pred = model.predict(x_test1)
mse = mean_squared_error(y_test1,y_pred)
print(f"\nMSE: {mse}")
rmse = mean_squared_error(y_test1,y_pred,squared=False)
print(f"\nRMSE: {rmse}")
mea = mean_absolute_error(y_test1,y_pred)
print(f"\nMEA: {mea}")
mdea = median_absolute_error(y_test1,y_pred)
print(f"\nMDEA: {mdea}")
r2 = r2_score(y_test1,y_pred)
print(f"\nR2 Square: {r2}")

MSE: 9.232196502057606

RMSE: 3.0384529784180643

MEA: 2.4473765432098755

MDEA: 2.05

R2 Square: 0.4888467660156992

In [28]:
dg = [2,3,4,5,6,7,8,9,10,15,20]
percentage = [0.5,0.6,0.7,0.8,0.9]
for i in dg:
    poly = PolynomialFeatures(degree = i,interaction_only=True)
    X_poly = poly.fit_transform(X[:,17:22])
    for j in percentage:
        x_train1, x_test1, y_train1, y_test1 = train_test_split(X_poly, Y, train_size=j, shuffle=True)
        model = LinearRegression()
        model.fit(x_train1,y_train1)
        y_pred = model.predict(x_test1)
        mse = mean_squared_error(y_test1,y_pred)
        print("MSE for polynomial degree %i and training data size %i percent is: %f "%(i,j*100,mse))
    print("\n")

MSE for polynomial degree 2 and training data size 50 percent is: 8.032974
MSE for polynomial degree 2 and training data size 60 percent is: 8.748204
MSE for polynomial degree 2 and training data size 70 percent is: 6.189427
MSE for polynomial degree 2 and training data size 80 percent is: 5.357230
MSE for polynomial degree 2 and training data size 90 percent is: 7.034785


MSE for polynomial degree 3 and training data size 50 percent is: 7.203191
MSE for polynomial degree 3 and training data size 60 percent is: 14.637425
MSE for polynomial degree 3 and training data size 70 percent is: 8.767345
MSE for polynomial degree 3 and training data size 80 percent is: 8.304647
MSE for polynomial degree 3 and training data size 90 percent is: 14.788274


MSE for polynomial degree 4 and training data size 50 percent is: 7.949656
MSE for polynomial degree 4 and training data size 60 percent is: 7.716663
MSE for polynomial degree 4 and training data size 70 percent is: 7.169247
MSE for polynomial degree 4 and training data size 80 percent is: 8.229708
MSE for polynomial degree 4 and training data size 90 percent is: 8.409770


MSE for polynomial degree 5 and training data size 50 percent is: 8.231736
MSE for polynomial degree 5 and training data size 60 percent is: 9.137661
MSE for polynomial degree 5 and training data size 70 percent is: 7.652941
MSE for polynomial degree 5 and training data size 80 percent is: 8.878085
MSE for polynomial degree 5 and training data size 90 percent is: 4.996637


MSE for polynomial degree 6 and training data size 50 percent is: 7.519742
MSE for polynomial degree 6 and training data size 60 percent is: 7.190869
MSE for polynomial degree 6 and training data size 70 percent is: 12.781874
MSE for polynomial degree 6 and training data size 80 percent is: 11.053027
MSE for polynomial degree 6 and training data size 90 percent is: 10.669511


MSE for polynomial degree 7 and training data size 50 percent is: 7.446697
MSE for polynomial degree 7 and training data size 60 percent is: 10.030179
MSE for polynomial degree 7 and training data size 70 percent is: 5.874781
MSE for polynomial degree 7 and training data size 80 percent is: 11.402909
MSE for polynomial degree 7 and training data size 90 percent is: 5.459455


MSE for polynomial degree 8 and training data size 50 percent is: 9.689654
MSE for polynomial degree 8 and training data size 60 percent is: 6.570703
MSE for polynomial degree 8 and training data size 70 percent is: 9.551091
MSE for polynomial degree 8 and training data size 80 percent is: 5.611191
MSE for polynomial degree 8 and training data size 90 percent is: 12.078527


MSE for polynomial degree 9 and training data size 50 percent is: 9.299106
MSE for polynomial degree 9 and training data size 60 percent is: 9.614772
MSE for polynomial degree 9 and training data size 70 percent is: 9.188053
MSE for polynomial degree 9 and training data size 80 percent is: 7.334790
MSE for polynomial degree 9 and training data size 90 percent is: 3.775644


MSE for polynomial degree 10 and training data size 50 percent is: 7.799304
MSE for polynomial degree 10 and training data size 60 percent is: 11.329983
MSE for polynomial degree 10 and training data size 70 percent is: 8.132948
MSE for polynomial degree 10 and training data size 80 percent is: 10.657897
MSE for polynomial degree 10 and training data size 90 percent is: 4.760541


MSE for polynomial degree 15 and training data size 50 percent is: 7.081895
MSE for polynomial degree 15 and training data size 60 percent is: 5.448025
MSE for polynomial degree 15 and training data size 70 percent is: 7.134242
MSE for polynomial degree 15 and training data size 80 percent is: 7.181351
MSE for polynomial degree 15 and training data size 90 percent is: 3.629214


MSE for polynomial degree 20 and training data size 50 percent is: 9.028551
MSE for polynomial degree 20 and training data size 60 percent is: 7.001530
MSE for polynomial degree 20 and training data size 70 percent is: 6.600254
MSE for polynomial degree 20 and training data size 80 percent is: 7.866960
MSE for polynomial degree 20 and training data size 90 percent is: 12.835150